import io
import os
import tempfile
from datetime import datetime
from fpdf import FPDF
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np


MARGIN = 25
PAGE_W = 210
CONTENT_W = PAGE_W - 2 * MARGIN


class ReportPDF(FPDF):
    def __init__(self, project_name=''):
        super().__init__()
        self.project_name = project_name
        self.set_auto_page_break(auto=True, margin=MARGIN)
        self.set_margins(MARGIN, MARGIN, MARGIN)
        self._is_title_page = False
        self._is_toc_page = False
        self._section_counter = 0
        self._subsection_counter = 0

    def header(self):
        if self._is_title_page or self._is_toc_page or self.page_no() <= 1:
            return
        self.set_font('Times', 'I', 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, self.project_name or 'DataPilot AI Report', 0, 0, 'L')
        self.cell(0, 8, 'DataPilot AI - Dataset Analysis Report', 0, 0, 'R')
        self.set_draw_color(180, 180, 180)
        self.set_line_width(0.3)
        self.line(MARGIN, self.get_y() + 9, PAGE_W - MARGIN, self.get_y() + 9)

    def footer(self):
        if self._is_title_page:
            return
        self.set_y(-20)
        self.set_draw_color(180, 180, 180)
        self.set_line_width(0.3)
        self.line(MARGIN, self.get_y(), PAGE_W - MARGIN, self.get_y())
        self.set_y(-18)
        self.set_font('Times', 'I', 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, f'Generated by DataPilot AI  |  {datetime.now().strftime("%B %d, %Y")}', 0, 0, 'L')
        self.cell(0, 10, f'Page {self.page_no() - 1}/{{nb}}', 0, 0, 'R')

    def set_heading_numbering(self, section, subsection=None):
        self._section_counter = section
        self._subsection_counter = subsection

    def section_title(self, number, title):
        self.ln(2)
        if self.get_y() > 245:
            self.add_page()
        self.set_font('Times', 'B', 14)
        self.set_text_color(25, 25, 25)
        self.cell(0, 10, f'{number}. {title}', 0, 1, 'L')
        y = self.get_y()
        self.set_draw_color(40, 40, 40)
        self.set_line_width(0.6)
        self.line(MARGIN, y, PAGE_W - MARGIN, y)
        self.ln(4)

    def sub_title(self, number, title):
        if self.get_y() > 250:
            self.add_page()
        self.ln(1)
        self.set_font('Times', 'B', 12)
        self.set_text_color(40, 40, 40)
        self.cell(0, 8, f'{number} {title}', 0, 1, 'L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Times', '', 12)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 7, text)
        self.ln(2)

    def justified_text(self, text):
        self.set_font('Times', '', 12)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 7, text, 0, 'J')
        self.ln(2)

    def kv_row(self, key, value, warn=False):
        self.set_font('Times', 'B', 11)
        self.set_text_color(60, 60, 60)
        self.cell(75, 7, key, 0, 0, 'L')
        self.set_font('Times', '', 11)
        if warn:
            self.set_text_color(200, 60, 10)
        else:
            self.set_text_color(30, 30, 30)
        self.cell(0, 7, str(value), 0, 1, 'L')

    def bullet_item(self, text, indent=10):
        x = self.get_x()
        self.set_font('Times', '', 11)
        self.set_text_color(30, 30, 30)
        self.cell(indent, 7, '')
        self.cell(5, 7, chr(8226))
        self.multi_cell(0, 7, text)

    def add_table(self, headers, rows, col_widths=None):
        if col_widths is None:
            col_widths = [CONTENT_W / len(headers)] * len(headers)

        def draw_header():
            self.set_font('Times', 'B', 9)
            self.set_fill_color(40, 40, 40)
            self.set_text_color(255, 255, 255)
            for i, header in enumerate(headers):
                self.cell(col_widths[i], 8, header, 1, 0, 'C', True)
            self.ln()

        draw_header()

        self.set_font('Times', '', 9)
        self.set_text_color(30, 30, 30)
        fill = False
        for row in rows:
            if self.get_y() > 260:
                self.add_page()
                draw_header()
                self.set_font('Times', '', 9)
                self.set_text_color(30, 30, 30)

            if fill:
                self.set_fill_color(245, 245, 248)
            else:
                self.set_fill_color(255, 255, 255)

            for i, cell in enumerate(row):
                text = str(cell) if cell is not None else '-'
                if len(text) > 35:
                    text = text[:32] + '...'
                self.cell(col_widths[i], 7, text, 1, 0, 'C', True)
            self.ln()
            fill = not fill
        self.ln(2)

    def add_chart_image(self, img_path, caption='', width=160):
        if self.get_y() + 75 > 270 - MARGIN:
            self.add_page()
        x = (PAGE_W - width) / 2
        self.image(img_path, x=x, w=width)
        if caption:
            self.set_font('Times', 'I', 10)
            self.set_text_color(100, 100, 100)
            self.cell(0, 6, caption, 0, 1, 'C')
        self.ln(3)

    def severity_badge(self, severity):
        colors = {
            'critical': (180, 30, 30),
            'warning': (200, 120, 10),
            'info': (40, 100, 200),
            'success': (30, 150, 70),
        }
        r, g, b = colors.get(severity, (100, 100, 100))
        self.set_fill_color(r, g, b)
        self.set_text_color(255, 255, 255)
        self.set_font('Times', 'B', 8)
        w = self.get_string_width(severity.upper()) + 6
        self.cell(w, 5.5, severity.upper(), 0, 0, 'C', True)
        self.set_text_color(30, 30, 30)


def _create_bar_chart(categories, values, title, filename):
    fig, ax = plt.subplots(figsize=(7, 3.5))
    colors = ['#2d2d2d', '#555555', '#777777', '#999999', '#bbbbbb',
              '#3a3a3a', '#4e4e4e', '#636363', '#808080', '#a0a0a0']
    bars = ax.bar(range(len(categories)), values, color=colors[:len(categories)],
                  edgecolor='white', linewidth=0.5)
    ax.set_xticks(range(len(categories)))
    ax.set_xticklabels(categories, rotation=45, ha='right', fontsize=8)
    ax.set_title(title, fontsize=11, fontweight='bold', color='#1a1a1a', pad=10)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#cccccc')
    ax.spines['bottom'].set_color('#cccccc')
    ax.tick_params(colors='#555555', labelsize=8)
    for bar in bars:
        height = bar.get_height()
        ax.annotate(f'{height:.0f}', xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 3), textcoords="offset points", ha='center', va='bottom',
                    fontsize=7, color='#555555')
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close(fig)


def _create_pie_chart(labels, sizes, title, filename):
    fig, ax = plt.subplots(figsize=(5, 4))
    colors = ['#2d2d2d', '#555555', '#777777', '#999999', '#bbbbbb',
              '#3a3a3a', '#4e4e4e', '#636363', '#808080', '#a0a0a0']
    wedges, texts, autotexts = ax.pie(
        sizes, labels=None, autopct='%1.1f%%', startangle=90,
        colors=colors[:len(labels)], pctdistance=0.8,
        textprops={'fontsize': 7, 'color': '#1a1a1a'}
    )
    ax.legend(labels, loc='center left', bbox_to_anchor=(1, 0.5), fontsize=7, frameon=False)
    ax.set_title(title, fontsize=11, fontweight='bold', color='#1a1a1a', pad=10)
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close(fig)


def _create_histogram(values, title, xlabel, filename):
    fig, ax = plt.subplots(figsize=(7, 3.5))
    numeric_vals = [v for v in values if v is not None and not np.isnan(v)]
    if not numeric_vals:
        plt.close(fig)
        return
    ax.hist(numeric_vals, bins=min(30, max(5, len(numeric_vals) // 5)),
            color='#2d2d2d', edgecolor='white', linewidth=0.5, alpha=0.85)
    ax.set_title(title, fontsize=11, fontweight='bold', color='#1a1a1a', pad=10)
    ax.set_xlabel(xlabel, fontsize=9, color='#555555')
    ax.set_ylabel('Frequency', fontsize=9, color='#555555')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#cccccc')
    ax.spines['bottom'].set_color('#cccccc')
    ax.tick_params(colors='#555555', labelsize=8)
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close(fig)


def _create_quality_chart(data_quality, filename):
    if not data_quality:
        return
    fig, axes = plt.subplots(1, 2, figsize=(7, 3))
    missing = data_quality.get('missingValues', 0)
    total_rows = data_quality.get('totalRows', 1) or 1
    present = total_rows - missing
    axes[0].pie([present, missing], labels=['Present', 'Missing'],
                colors=['#2d2d2d', '#999999'], autopct='%1.1f%%',
                textprops={'fontsize': 8}, startangle=90)
    axes[0].set_title('Missing Values', fontsize=10, fontweight='bold', color='#1a1a1a')

    duplicates = data_quality.get('duplicateRows', 0)
    unique = total_rows - duplicates
    axes[1].pie([unique, duplicates], labels=['Unique', 'Duplicates'],
                colors=['#555555', '#bbbbbb'], autopct='%1.1f%%',
                textprops={'fontsize': 8}, startangle=90)
    axes[1].set_title('Duplicate Rows', fontsize=10, fontweight='bold', color='#1a1a1a')

    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close(fig)


def _create_column_type_chart(columns, filename):
    type_counts = {}
    for col in columns:
        dt = col.get('dataType', 'string')
        type_counts[dt] = type_counts.get(dt, 0) + 1
    labels = list(type_counts.keys())
    sizes = list(type_counts.values())
    if not labels:
        return
    fig, ax = plt.subplots(figsize=(5, 3.5))
    color_map = {'number': '#2d2d2d', 'string': '#666666', 'date': '#444444',
                 'boolean': '#888888', 'unknown': '#aaaaaa'}
    bar_colors = [color_map.get(l, '#555555') for l in labels]
    bars = ax.bar(labels, sizes, color=bar_colors, edgecolor='white', linewidth=0.5)
    ax.set_title('Column Data Types', fontsize=11, fontweight='bold', color='#1a1a1a', pad=10)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    for bar in bars:
        h = bar.get_height()
        ax.annotate(f'{int(h)}', xy=(bar.get_x() + bar.get_width() / 2, h),
                    xytext=(0, 3), textcoords="offset points", ha='center', fontsize=9, color='#1a1a1a')
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close(fig)


def generate_report(analysis_data, project_name='Dataset', dataset_name=''):
    pdf = ReportPDF(project_name)
    pdf.alias_nb_pages()
    pdf._is_title_page = True
    pdf.add_page()

    tmpdir = tempfile.mkdtemp()
    chart_files = []
    figure_counter = [0]

    def next_figure():
        figure_counter[0] += 1
        return figure_counter[0]

    try:
        # ════════════════════════════════════════════
        # TITLE PAGE
        # ════════════════════════════════════════════
        pdf.ln(35)
        pdf.set_font('Times', 'B', 26)
        pdf.set_text_color(25, 25, 25)
        pdf.cell(0, 14, 'DataPilot AI', 0, 1, 'C')
        pdf.ln(3)
        pdf.set_font('Times', '', 16)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 10, 'Dataset Analysis Report', 0, 1, 'C')
        pdf.ln(6)

        pdf.set_draw_color(25, 25, 25)
        pdf.set_line_width(0.8)
        pdf.line(70, pdf.get_y(), PAGE_W - 70, pdf.get_y())
        pdf.ln(8)

        pdf.set_font('Times', 'B', 18)
        pdf.set_text_color(25, 25, 25)
        pdf.cell(0, 12, project_name, 0, 1, 'C')
        if dataset_name:
            pdf.set_font('Times', '', 12)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(0, 8, f'Dataset: {dataset_name}', 0, 1, 'C')

        pdf.ln(25)
        pdf.set_font('Times', '', 11)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 7, f'Report Generated: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}', 0, 1, 'C')
        pdf.ln(2)
        pdf.cell(0, 7, 'Prepared by DataPilot AI Analysis Engine', 0, 1, 'C')

        # ════════════════════════════════════════════
        # TABLE OF CONTENTS
        # ════════════════════════════════════════════
        pdf._is_title_page = False
        pdf._is_toc_page = True
        pdf.add_page()
        pdf.set_font('Times', 'B', 16)
        pdf.set_text_color(25, 25, 25)
        pdf.cell(0, 12, 'Table of Contents', 0, 1, 'L')
        pdf.set_draw_color(25, 25, 25)
        pdf.set_line_width(0.5)
        pdf.line(MARGIN, pdf.get_y(), PAGE_W - MARGIN, pdf.get_y())
        pdf.ln(6)

        toc_items = [
            ('1', 'Executive Summary'),
            ('2', 'Dataset Profile'),
            ('3', 'Column Analysis'),
            ('4', 'Statistical Summary'),
            ('5', 'Data Quality Report'),
            ('6', 'Chart Recommendations'),
            ('7', 'AI Insights'),
        ]
        pdf.set_font('Times', '', 12)
        pdf.set_text_color(40, 40, 40)
        for num, item in toc_items:
            pdf.cell(12, 9, num + '.', 0, 0, 'R')
            pdf.cell(5, 9, '')
            pdf.cell(0, 9, item, 0, 1, 'L')

        pdf._is_toc_page = False

        # ════════════════════════════════════════════
        # 1. EXECUTIVE SUMMARY
        # ════════════════════════════════════════════
        pdf.add_page()
        pdf.section_title('1', 'Executive Summary')

        summary = analysis_data.get('datasetSummary', {})
        dq = analysis_data.get('dataQuality', {})
        cols = analysis_data.get('columnAnalysis', [])
        insights = analysis_data.get('aiInsights', [])

        total_rows = summary.get('totalRows', 0)
        total_cols = summary.get('totalColumns', 0)
        file_size = summary.get('datasetSize', 0)
        missing = dq.get('missingValues', 0) if dq else 0
        duplicates = dq.get('duplicateRows', 0) if dq else 0
        num_insights = len(insights)

        size_str = f'{file_size / 1024 / 1024:.2f} MB' if file_size else 'N/A'

        pdf.justified_text(
            f'This report presents a comprehensive analysis of the dataset '
            f'"{dataset_name or project_name}". The dataset contains {total_rows:,} rows '
            f'and {total_cols} columns with a total size of {size_str}. The analysis was '
            f'performed by DataPilot AI, covering data profiling, statistical analysis, '
            f'data quality assessment, and automated insight generation.'
        )

        if missing > 0 or duplicates > 0:
            pdf.justified_text(
                f'Key findings include {missing:,} missing values and {duplicates:,} '
                f'duplicate rows detected. These issues may affect the reliability of '
                f'downstream analysis and should be addressed before further processing.'
            )

        pdf.ln(1)
        pdf.sub_title('1.1', 'Key Metrics')
        pdf.kv_row('Dataset Name', dataset_name or 'N/A')
        pdf.kv_row('Total Rows', f'{total_rows:,}')
        pdf.kv_row('Total Columns', total_cols)
        pdf.kv_row('File Size', size_str)
        pdf.kv_row('File Type', summary.get('fileType', 'N/A'))
        pdf.kv_row('Upload Date', str(summary.get('uploadDate', 'N/A')))
        pdf.kv_row('Missing Values', f'{missing:,}', warn=missing > 0)
        pdf.kv_row('Duplicate Rows', f'{duplicates:,}', warn=duplicates > 0)
        pdf.kv_row('Insights Generated', num_insights)

        # ════════════════════════════════════════════
        # 2. DATASET PROFILE
        # ════════════════════════════════════════════
        pdf.add_page()
        pdf.section_title('2', 'Dataset Profile')

        if dq:
            pdf.sub_title('2.1', 'Data Composition')
            numeric_cols = dq.get('numericColumns', [])
            categorical_cols = dq.get('categoricalColumns', [])
            date_cols = dq.get('dateColumns', [])

            pdf.kv_row('Numeric Columns', len(numeric_cols))
            pdf.kv_row('Categorical Columns', len(categorical_cols))
            pdf.kv_row('Date Columns', len(date_cols))
            pdf.kv_row('Missing Percentage', f"{dq.get('missingPercentage', 0):.2f}%")
            pdf.kv_row('Duplicate Percentage', f"{dq.get('duplicatePercentage', 0):.2f}%")

            if numeric_cols:
                pdf.ln(1)
                pdf.sub_title('2.2', 'Numeric Columns')
                for c in numeric_cols:
                    pdf.bullet_item(c)

            if categorical_cols:
                pdf.ln(1)
                pdf.sub_title('2.3', 'Categorical Columns')
                for c in categorical_cols:
                    pdf.bullet_item(c)

            if date_cols:
                pdf.ln(1)
                pdf.sub_title('2.4', 'Date Columns')
                for c in date_cols:
                    pdf.bullet_item(c)
        else:
            pdf.body_text('Profile data is not available for this dataset.')

        if cols:
            chart_path = os.path.join(tmpdir, 'col_types.png')
            chart_files.append(chart_path)
            _create_column_type_chart(cols, chart_path)
            fig_num = next_figure()
            pdf.add_chart_image(chart_path, f'Figure {fig_num}: Distribution of Column Data Types')

        # ════════════════════════════════════════════
        # 3. COLUMN ANALYSIS
        # ════════════════════════════════════════════
        pdf.add_page()
        pdf.section_title('3', 'Column Analysis')

        if cols:
            headers = ['Column Name', 'Data Type', 'Unique Values', 'Missing', 'Missing %']
            widths = [50, 30, 35, 35, 40]
            rows = []
            for col in cols:
                rows.append([
                    col.get('columnName', ''),
                    col.get('dataType', ''),
                    f"{col.get('uniqueCount', 0):,}",
                    f"{col.get('missingCount', 0):,}",
                    f"{col.get('missingPercentage', 0):.1f}%"
                ])
            pdf.add_table(headers, rows, widths)
        else:
            pdf.body_text('Column analysis data is not available.')

        # ════════════════════════════════════════════
        # 4. STATISTICAL SUMMARY
        # ════════════════════════════════════════════
        pdf.add_page()
        pdf.section_title('4', 'Statistical Summary')

        statistics = analysis_data.get('statistics', [])
        if statistics:
            headers = ['Column', 'Mean', 'Median', 'Std Dev', 'Min', 'Max']
            widths = [40, 30, 30, 30, 30, 30]
            rows = []
            for stat in statistics:
                def fmt(v):
                    if v is None:
                        return '-'
                    try:
                        return f'{float(v):.2f}'
                    except (ValueError, TypeError):
                        return str(v)
                rows.append([
                    stat.get('columnName', ''),
                    fmt(stat.get('mean')),
                    fmt(stat.get('median')),
                    fmt(stat.get('stdDev')),
                    fmt(stat.get('min')),
                    fmt(stat.get('max')),
                ])
            pdf.add_table(headers, rows, widths)

            raw_data = analysis_data.get('rawNumericData', {})
            if cols:
                first_numeric = next((col for col in cols if col.get('isNumeric')), None)
                if first_numeric:
                    col_name = first_numeric.get('columnName', '')
                    num_vals = raw_data.get(col_name, [])
                    if not num_vals and statistics:
                        num_vals = [float(statistics[0].get('mean', 0) or 0)]
                    if num_vals:
                        chart_path = os.path.join(tmpdir, 'histogram.png')
                        chart_files.append(chart_path)
                        _create_histogram(num_vals, f'Distribution Overview ({col_name})', col_name, chart_path)
                        fig_num = next_figure()
                        pdf.add_chart_image(chart_path, f'Figure {fig_num}: Histogram of {col_name}')
        else:
            pdf.body_text('Statistical data is not available for this dataset.')

        # ════════════════════════════════════════════
        # 5. DATA QUALITY REPORT
        # ════════════════════════════════════════════
        pdf.add_page()
        pdf.section_title('5', 'Data Quality Report')

        if dq:
            pdf.sub_title('5.1', 'Quality Metrics')
            pdf.kv_row('Total Rows', f"{dq.get('totalRows', 0):,}")
            pdf.kv_row('Missing Values', f"{dq.get('missingValues', 0):,}", warn=dq.get('missingValues', 0) > 0)
            pdf.kv_row('Missing Percentage', f"{dq.get('missingPercentage', 0):.2f}%", warn=dq.get('missingPercentage', 0) > 0)
            pdf.kv_row('Duplicate Rows', f"{dq.get('duplicateRows', 0):,}", warn=dq.get('duplicateRows', 0) > 0)
            pdf.kv_row('Duplicate Percentage', f"{dq.get('duplicatePercentage', 0):.2f}%", warn=dq.get('duplicatePercentage', 0) > 0)

            chart_path = os.path.join(tmpdir, 'quality.png')
            chart_files.append(chart_path)
            _create_quality_chart(dq, chart_path)
            fig_num = next_figure()
            pdf.add_chart_image(chart_path, f'Figure {fig_num}: Data Quality Overview', width=150)

            issues = analysis_data.get('issues', [])
            if issues:
                pdf.sub_title('5.2', 'Detected Issues')
                for issue in issues:
                    pdf.set_font('Times', 'B', 10)
                    pdf.set_text_color(30, 30, 30)
                    sev = issue.get('severity', 'info')
                    pdf.cell(10, 7, '')
                    pdf.severity_badge(sev)
                    pdf.cell(4, 7, '')
                    pdf.set_font('Times', '', 10)
                    pdf.set_text_color(50, 50, 50)
                    msg = issue.get('message', '')
                    pdf.multi_cell(0, 6, msg)
                    pdf.ln(2)
        else:
            pdf.body_text('Quality report data is not available.')

        # ════════════════════════════════════════════
        # 6. CHART RECOMMENDATIONS
        # ════════════════════════════════════════════
        pdf.add_page()
        pdf.section_title('6', 'Chart Recommendations')

        charts = analysis_data.get('chartRecommendations', [])
        if charts:
            for i, rec in enumerate(charts):
                if pdf.get_y() > 240:
                    pdf.add_page()
                pdf.set_font('Times', 'B', 11)
                pdf.set_text_color(25, 25, 25)
                chart_type = rec.get('type', 'chart').upper()
                pdf.cell(0, 7, f'6.{i + 1}  {chart_type} Chart', 0, 1)

                pdf.set_font('Times', 'B', 10)
                pdf.set_text_color(40, 40, 40)
                pdf.cell(0, 6, f'Title: {rec.get("title", "")}', 0, 1)

                pdf.set_font('Times', '', 10)
                pdf.set_text_color(80, 80, 80)
                cols_list = rec.get('columns', [])
                if isinstance(cols_list, list):
                    cols_str = ', '.join(cols_list)
                else:
                    cols_str = str(cols_list)
                pdf.cell(0, 6, f'Columns: {cols_str}', 0, 1)

                pdf.set_font('Times', 'I', 10)
                pdf.set_text_color(70, 70, 70)
                pdf.multi_cell(0, 6, f'Reason: {rec.get("reason", "")}')
                pdf.ln(3)
        else:
            pdf.body_text('No chart recommendations available.')

        # ════════════════════════════════════════════
        # 7. AI INSIGHTS
        # ════════════════════════════════════════════
        pdf.add_page()
        pdf.section_title('7', 'AI Insights')

        if insights:
            for i, insight in enumerate(insights):
                if pdf.get_y() > 248:
                    pdf.add_page()

                pdf.set_font('Times', 'B', 12)
                pdf.set_text_color(25, 25, 25)
                title = insight.get('title', f'Insight {i + 1}')
                pdf.cell(0, 8, f'{i + 1}. {title}', 0, 1)

                pdf.set_font('Times', '', 11)
                pdf.set_text_color(50, 50, 50)
                pdf.multi_cell(0, 6.5, insight.get('description', ''))
                pdf.ln(1)

                sev = insight.get('severity', 'info')
                conf = insight.get('confidence', 0)
                pdf.set_font('Times', '', 9)
                pdf.set_text_color(90, 90, 90)
                pdf.cell(15, 5, '')
                pdf.severity_badge(sev)
                pdf.cell(5, 5, '')
                pdf.cell(0, 5, f'Confidence: {conf}%', 0, 1)
                pdf.ln(4)
        else:
            pdf.body_text('No AI insights generated for this dataset yet.')

        # ════════════════════════════════════════════
        # OUTPUT
        # ════════════════════════════════════════════
        pdf_path = os.path.join(tmpdir, f'{project_name}_report.pdf')
        pdf.output(pdf_path)
        return pdf_path

    finally:
        for f in chart_files:
            try:
                os.remove(f)
            except OSError:
                pass
        try:
            os.rmdir(tmpdir)
        except OSError:
            pass
