import random
from typing import List, Tuple

INTENT_TEMPLATES = {
    'REMOVE_COLUMNS': [
        'remove {col}', 'delete {col}', 'drop {col}', 'hide {col}',
        'remove columns {col}', 'delete columns {col} and {col2}',
        'drop column {col}', 'get rid of {col}', 'remove personal information',
        'strip {col}', 'exclude {col}', 'omit {col}',
        'can you remove {col}', 'I want to delete {col}',
        'please drop the {col} column', 'remove {col} from the dataset',
        'get rid of the {col} column', 'eliminate {col}',
        'remove {col} and {col2}', 'drop both {col} and {col2}',
        'exclude columns {col} and {col2}', 'hide the {col} column from view',
        'I don\'t need {col} anymore', 'remove all columns named {col}',
        'strip out {col} from the data', 'delete the {col} field',
        'drop {col} column please', 'remove {col} entirely',
        'get {col} out of here', 'toss out {col}',
        'nix the {col} column', 'scrap {col}',
    ],
    'FILTER': [
        'show only {col} department', 'filter {col} greater than {val}',
        'keep rows where {col} is {val}', 'filter salary greater than 50000',
        'show only rows where {col} equals {val}', 'keep {col} is {val}',
        'filter out where {col} is less than {val}', 'limit to {col} {val}',
        'select where {col} is {val}', 'show only {val} in {col}',
        'filter {col} above {val}', 'I only want to see {col} where it\'s {val}',
        'show me entries with {col} equal to {val}',
        'filter the data to only include {col} {val}',
        'can you filter by {col} being {val}',
        'show {col} that are greater than {val}',
        'what about {col} less than {val}',
        'only show records where {col} exceeds {val}',
        'filter out everything except {val} in {col}',
        'restrict to {col} above {val}',
        'show rows with {col} below {val}',
        'keep only {col} that is {val}',
        'filter dataset to {col} equals {val}',
        'I need rows where {col} is more than {val}',
        'show me only when {col} is under {val}',
        'exclude rows where {col} is {val}',
        'filter to only include {col} >= {val}',
        'limit results to {col} between {val}',
        'show {col} greater than or equal to {val}',
        'keep rows matching {col} = {val}',
        'give me everything where {col} is {val}',
        'show me just the {val} ones in {col}',
    ],
    'SORT': [
        'sort by {col}', 'order by {col}', 'arrange by {col}',
        'sort {col} descending', 'order {col} ascending',
        'arrange {col} from high to low', 'sort {col} alphabetically',
        'sort by {col} in reverse', 'order by {col} desc', 'order by {col} asc',
        'sort the data by {col}', 'can you order by {col}',
        'arrange the rows by {col}', 'I want to sort by {col}',
        'sort {col} from low to high', 'rank by {col}',
        'sort {col} Z to A', 'sort {col} A to Z',
        'order the dataset by {col} descending',
        'arrange everything by {col}',
        'sort by {col} please', 'sort the {col} column',
        'put the data in order of {col}',
        'reorder by {col}', 'can you sort by {col} desc?',
        'sort {col} from smallest to largest',
        'sort {col} largest to smallest',
        'arrange {col} in descending order',
        'sort rows by {col}', 'order records by {col}',
        'line up the data by {col}',
    ],
    'GROUP_BY': [
        'group by {col}', 'group dataset by {col}', 'aggregate by {col}',
        'summarize by {col}', 'group by {col} and calculate sum',
        'group by {col} and find average', 'run group by on {col}',
        'can you group the data by {col}', 'split the data by {col}',
        'group records by {col}', 'aggregate the dataset by {col}',
        'summarize data grouped by {col}',
        'I want to see a breakdown by {col}',
        'break down the data by {col}',
        'give me a summary by {col}',
        'group everything by {col}',
        'segment the data by {col}',
        'categorize by {col}', 'partition by {col}',
        'group by {col} and show counts',
        'group by {col} with totals',
        'group by {col} and compute averages',
        'organize by {col}',
        'cluster by {col}',
        'bin the data by {col}',
        'separate by {col}',
    ],
    'RENAME_COLUMN': [
        'rename {col} to {col2}', 'change name of {col} to {col2}',
        'rename income to salary', 'rename column {col} as {col2}',
        'change {col} header to {col2}', 'rename column {col} to {col2}',
        'can you rename {col} to {col2}',
        'I want to rename {col} as {col2}',
        'change the column name {col} to {col2}',
        'rename the {col} column to {col2}',
        'update column name from {col} to {col2}',
        'replace the name {col} with {col2}',
        'set {col} column name to {col2}',
        'what if we call {col} instead {col2}',
        'rename {col} header to {col2}',
        'change {col} to be called {col2}',
        'switch column name from {col} to {col2}',
        'alter the name of {col} to {col2}',
        'modify {col} column name to {col2}',
        'let\'s rename {col} to {col2}',
        'relabel {col} as {col2}',
        'call {col} column {col2} instead',
        'transform {col} name to {col2}',
        'swap column name {col} for {col2}',
    ],
    'AGGREGATE': [
        'calculate average {col}', 'sum of {col}', 'max {col}', 'min {col}',
        'median {col}', 'find mean of {col}', 'get standard deviation of {col}',
        'calculate total {col}', 'average {col} by {col2}',
        'compute average of {col}', 'get the maximum value of {col}',
        'what is the average {col}', 'give me the mean {col}',
        'show me the average {col}', 'I need the average {col}',
        'can you calculate the mean {col}', 'what\'s the typical {col} value',
        'give me the average {col}', '{col} average please', 'average {col}?',
        'compute mean of {col}', 'how high is the average {col}',
        'what\'s the mean value for {col}', 'average {col} across all rows',
        'total sum of {col}', 'add up all {col} values',
        'what is the total {col}', 'give me the sum of {col}',
        'sum {col}', 'total {col}?',
        'find max in {col}', 'what\'s the highest {col}',
        'show me the peak {col}', 'maximum value of {col}',
        'find the top {col} value', 'what is the largest {col}',
        'find min in {col}', 'what\'s the lowest {col}',
        'show minimum {col}', 'minimum value of {col}',
        'what is the smallest {col}', 'find the bottom {col} value',
        'median of {col}', 'what\'s the middle value of {col}',
        'show me the median {col}',
        'standard deviation of {col}', 'how spread out is {col}',
        'variance of {col}', 'what is the std dev of {col}',
        'compute the sum of {col}', 'add {col} together',
        'what does {col} add up to', 'total up {col}',
    ],
    'REMOVE_DUPLICATES': [
        'remove duplicates', 'remove duplicate rows', 'delete duplicate rows',
        'deduplicate', 'clean duplicates', 'remove repeat rows',
        'drop duplicates', 'clear duplicates', 'find and remove duplicates',
        'get rid of duplicate entries', 'eliminate duplicate records',
        'can you remove duplicates', 'I want to deduplicate the data',
        'please remove any duplicate rows',
        'remove rows that are duplicated', 'clean up duplicate entries',
        'drop all duplicate records', 'delete repeats',
        'remove repeated rows', 'eliminate repeats from the dataset',
        'clean out duplicate data', 'get rid of repeated entries',
        'how about removing duplicates', 'strip out duplicate rows',
        'remove duplicates please', 'dedupe the dataset',
        'remove the duplicate records', 'filter out duplicates',
        'cull duplicate rows', 'purge duplicates',
        'remove identical rows', 'cleanse duplicates',
    ],
    'FILL_MISSING': [
        'fill missing values', 'replace nulls', 'fill empty cells',
        'fill missing in {col} with {val}', 'replace nulls in {col} with mean',
        'fill empty values with {val}', 'impute missing values',
        'fill empty cells with zero', 'replace missing values with mode',
        'can you fill in the missing data', 'impute the nulls',
        'fill null values with averages', 'replace blanks with zero',
        'handle the missing values', 'fill in the gaps',
        'replace NaN values', 'fill missing entries',
        'populate empty cells', 'what about the null values',
        'fill the missing data please', 'impute missing in {col}',
        'replace nulls with median', 'fill empty with mean',
        'handle missing data in {col}', 'fill gaps in {col}',
        'substitute nulls with {val}', 'put {val} where data is missing',
        'fill in blanks with {val}', 'use {val} for missing entries',
        'replace missing with {val}', 'fill nulls using {val}',
    ],
    'REMOVE_MISSING': [
        'remove missing rows', 'drop empty rows', 'delete rows with null values',
        'remove nulls', 'drop rows with missing {col}',
        'delete empty rows in {col}', 'remove missing data',
        'can you drop the rows with nulls',
        'delete any rows that have missing values',
        'remove entries with blanks', 'get rid of incomplete rows',
        'drop rows where data is missing', 'eliminate rows with nulls',
        'clean out missing entries', 'remove rows containing null values',
        'delete records with empty fields',
        'drop rows with NaN in {col}',
        'remove {col} rows that are empty',
        'delete entries missing {col}',
        'get rid of rows without {col}',
        'strip out rows with null {col}',
        'remove incomplete records', 'drop incomplete entries',
        'delete rows where {col} is blank',
        'remove records missing data',
        'clean up null rows', 'purge missing rows',
        'eliminate empty rows from {col}',
        'remove rows lacking {col}',
        'drop records with empty {col}',
    ],
    'CONVERT_TYPE': [
        'convert {col} to number', 'change type of {col} to string',
        'cast {col} to date', 'convert column {col} to boolean',
        'convert {col} type to float', 'change type of {col}',
        'can you convert {col} to numeric',
        'I need {col} as a number', 'make {col} a string column',
        'cast {col} to integer', 'transform {col} to date type',
        'change {col} from text to number',
        'convert {col} to datetime format',
        'make {col} numeric', 'turn {col} into a number',
        'switch {col} to text type', 'change data type of {col}',
        'retype {col} as {val}', 'convert {col} to {val} type',
        'cast column {col} to {val}',
        'transform column {col} to {val}',
        'change {col} to be {val}', 'make {col} a {val} column',
        'set {col} type to {val}', 'reformat {col} as {val}',
        'convert {col} values to {val}',
    ],
    'DESCRIBE': [
        'describe dataset', 'summarize data', 'show dataset profile',
        'profile this dataset', 'get data summary', 'describe the table',
        'show info of dataset', 'dataset overview',
        'give me a summary of the data', 'what does this dataset look like',
        'tell me about this dataset', 'show me the data profile',
        'describe the data', 'what\'s in this dataset',
        'overview of the dataset', 'summarize the dataset',
        'can you describe this data', 'show dataset statistics',
        'what are the columns', 'show me the schema',
        'describe the table structure', 'give me dataset info',
        'what does the data contain', 'show data overview',
        'tell me about this table', 'profile the data',
        'show summary statistics', 'describe what\'s in the data',
        'what\'s the structure of this dataset',
        'give me an overview of the data',
    ],
    'SHOW_TOP': [
        'show top 10 rows', 'display first 5 records', 'show head of data',
        'show first {val} rows', 'show top rows', 'display head',
        'print first few lines', 'show me the first rows',
        'show the first {val} entries', 'display the top records',
        'give me the first {val} rows', 'what are the first few rows',
        'show the head of the dataset', 'show top {val} records',
        'display first {val} entries', 'show me {val} rows from the top',
        'first {val} rows please', 'show the beginning of the data',
        'preview the first {val} rows', 'show the first few records',
        'can you show the first {val}', 'give me a preview of the top rows',
        'display the first {val} lines',
        'show me the head of the table', 'peek at the first {val} rows',
        'show the first {val} items', 'initial {val} rows',
        'show me the earliest records', 'first entries in the dataset',
    ],
    'SHOW_BOTTOM': [
        'show bottom 5 rows', 'display last 10 records', 'show tail',
        'show bottom rows', 'display tail', 'show last {val} rows',
        'show me the last rows', 'show the bottom {val} entries',
        'display the last records', 'give me the last {val} rows',
        'what are the last few rows', 'show the tail of the dataset',
        'show bottom {val} records', 'display last {val} entries',
        'show me {val} rows from the bottom', 'last {val} rows please',
        'show the end of the data', 'preview the last {val} rows',
        'show me the tail of the table', 'can you show the last {val}',
        'give me a preview of the bottom rows', 'display the last {val} lines',
        'show the last {val} items', 'final {val} rows',
        'show me the latest records', 'last entries in the dataset',
        'show the bottom entries', 'display the tail',
    ],
    'COUNT': [
        'count total records', 'how many rows are there', 'get row count',
        'count rows', 'number of rows', 'total record count',
        'get length of dataset', 'how many entries are there',
        'what is the row count', 'count the number of records',
        'how many records do we have', 'total rows in dataset',
        'give me the row count', 'show me the number of rows',
        'how many data points are there', 'count all rows',
        'how many items in the dataset', 'get the total count',
        'what is the total number of records',
        'show the dataset size in rows', 'how many observations',
        'count of records', 'number of entries',
        'how many samples are there', 'total number of data points',
        'what\'s the row total', 'give me a count of all rows',
        'how big is this dataset in rows', 'dataset row count please',
        'tell me how many rows',
    ],
    'CALCULATE': [
        'calculate bonus', 'compute total cost', 'evaluate net profit',
        'calculate formula', 'compute {col} minus {col2}',
        'calculate new column', 'compute percentage',
        'can you calculate the difference between {col} and {col2}',
        'compute {col} plus {col2}', 'what is {col} divided by {col2}',
        'calculate {col} times {col2}', 'derive a new column from {col}',
        'create a calculated field', 'compute a new metric',
        'calculate the ratio of {col} to {col2}',
        'what\'s the difference between {col} and {col2}',
        'compute profit as {col} minus {col2}',
        'calculate margin from {col} and {col2}',
        'evaluate {col} divided by {col2}',
        'what would {col} times {col2} be',
        'calculate the growth rate',
        'compute year over year change',
        'derive revenue per unit from {col} and {col2}',
        'calculate cost efficiency',
        'compute the profit margin',
    ],
    'TOP_N': [
        'top 5 products by revenue', 'show me the top 10 employees by salary',
        'bottom 3 regions by sales', 'show top 5 rows by {col}',
        'what are the top {val} {col}', 'give me the best {val} {col}',
        'show the highest {val} by {col}', 'top {val} entries by {col}',
        'rank the top {val} {col}', 'show the bottom {val} by {col}',
        'what are the worst {val} {col}', 'show me the top performers',
        'give me the top {val} records by {col}',
        'list the {val} highest {col}', 'list the {val} lowest {col}',
        'show the {val} best {col}', 'show the {val} worst {col}',
        'which {val} have the highest {col}', 'what are the leading {col}',
        'show me the biggest {val} by {col}',
        'top {val} items ranked by {col}',
        'bottom {val} items ranked by {col}',
        'give me the top {val} values of {col}',
        'show top {val} performers in {col}',
        'what are the top {val} by {col}',
        'show me the highest {val} records',
        'rank the {val} best {col}',
        'identify the top {val} {col}',
        'find the leading {val} by {col}',
        'show the {val} most {col}',
    ],
    'COMPARE': [
        'compare sales between East and West',
        'how does Marketing differ from Sales in budget',
        'difference in attrition between departments',
        'compare {col} between {val} and {col2}',
        'what\'s the difference between {col} and {col2}',
        'how do {col} values compare across {val}',
        'compare the performance of {val} vs {col2}',
        'which is higher, {col} or {col2}',
        'contrast {col} between groups',
        'how does {col} differ between {val} categories',
        'compare {col} before and after',
        'what\'s the gap between {col} and {col2}',
        'is {col} higher or lower than {col2}',
        'how much more is {col} compared to {col2}',
        'compare the averages of {col} and {col2}',
        'which department has higher {col}',
        'difference in {col} between {val} and {col2}',
        'compare {col} across all {val}',
        'how do the groups compare in {col}',
        'what are the differences in {col}',
        'show me a comparison of {col}',
        'compare {col} side by side',
        'which option has better {col}',
        'how does {col} stack up',
        'compare totals for {col}',
        'contrast {col} between {val}',
        'what\'s the relative performance',
        'show differences in {col}',
        'how do the numbers compare',
        'compare {col} metrics across {val}',
    ],
    'PERCENTAGE': [
        'what percentage of employees are in Engineering',
        'what portion of revenue comes from Product A',
        'ratio of active to inactive customers',
        'what percent of {col} is {val}',
        'how much of the total is {col}',
        'what share of {col} belongs to {val}',
        'percentage breakdown by {col}',
        'what fraction of records have {col} = {val}',
        'how many percent are in {val} category',
        'what\'s the proportion of {val} in {col}',
        'show the percentage distribution of {col}',
        'what percent of the dataset is {val}',
        'calculate the share of {col}',
        'what portion of total {col} is {val}',
        'how big a share does {val} represent',
        'what\'s the percentage of {col} that is {val}',
        'what ratio of {col} is {val}',
        'express {col} as a percentage',
        'what is the {col} percentage for {val}',
        'how many percent of rows have {col} {val}',
        'show me the {col} proportions',
        'what\'s the split by {col}',
        'calculate percentage of {val} in {col}',
        'what is the market share by {col}',
        'show percentage share for each {col}',
        'how much does {val} contribute to {col}',
        'what is the relative percentage of {col}',
        'express the distribution as percentages',
    ],
    'DISTRIBUTION': [
        'show salary distribution', 'what is the age distribution',
        'distribution of sales by region', 'show the distribution of {col}',
        'how is {col} distributed', 'what does the {col} distribution look like',
        'show me the frequency of {col}', 'histogram of {col}',
        'what are the value counts for {col}', 'show the spread of {col}',
        'how are values distributed in {col}',
        'give me the distribution of {col}',
        'what is the frequency distribution of {col}',
        'show how {col} values are spread',
        'display the distribution pattern of {col}',
        'what\'s the shape of the {col} distribution',
        'are values in {col} evenly distributed',
        'show me a breakdown of {col} values',
        'how frequently does each {col} value occur',
        'what are the most common {col} values',
        'show the range and spread of {col}',
        'is {col} normally distributed',
        'what\'s the variance in {col}',
        'show the dispersion of {col}',
        'how varied is the {col} data',
        'show the histogram for {col}',
        'give me value frequencies for {col}',
        'what is the density of {col} values',
    ],
    'TREND': [
        'how has revenue changed over time', 'show hiring trend by month',
        'is attrition increasing', 'what is the trend in sales',
        'show the {col} trend over time', 'is {col} increasing or decreasing',
        'what direction is {col} trending', 'show me the {col} trend line',
        'how has {col} evolved', 'what\'s the trend in {col}',
        'is there an upward trend in {col}',
        'are {col} values going up or down',
        'show the monthly trend of {col}',
        'what does the {col} trajectory look like',
        'is {col} growing over time', 'show year over year {col} trend',
        'how is {col} changing month to month',
        'what\'s happening with {col} over time',
        'is the {col} trend positive or negative',
        'show the trend in {col} across periods',
        'are we seeing improvement in {col}',
        'what\'s the direction of the {col} trend',
        'show me how {col} has performed over time',
        'is there a declining trend in {col}',
        'track the {col} trend over the last period',
        'how does the {col} trend look',
        'show the historical trend of {col}',
        'is {col} trending upwards',
        'what pattern does {col} follow over time',
    ],
}

COLS = ['Salary', 'Department', 'Revenue', 'Sales', 'Age', 'Region', 'Product', 'Quantity', 'Discount', 'Date', 'Customer_ID', 'Churn', 'Budget', 'Profit', 'Margin', 'Employee_Name', 'Department_Name', 'Performance_Score', 'Hire_Date', 'Status']
VALS = ['Sales', 'Marketing', '50000', '100', 'East', 'West', 'Active', 'Yes', 'No', '0', '30', 'Completed', 'Engineering', 'HR', 'Finance', '100000', '200', 'North', 'South', '2024', 'Full-Time', 'Part-Time', 'Manager', 'Senior', 'Junior']

def generate_command_samples(num_samples: int = 1000) -> Tuple[List[str], List[str]]:
    texts = []
    labels = []

    for intent, templates in INTENT_TEMPLATES.items():
        for _ in range(num_samples):
            template = random.choice(templates)

            col1 = random.choice(COLS)
            col2 = random.choice([c for c in COLS if c != col1])
            val = random.choice(VALS)

            cmd = template.replace('{col}', col1).replace('{col2}', col2).replace('{val}', val)

            if random.random() > 0.8:
                cmd = cmd.upper()
            elif random.random() > 0.8:
                cmd = cmd.lower()
            elif random.random() > 0.9:
                words = cmd.split()
                if len(words) > 1:
                    idx = random.randint(0, len(words) - 1)
                    words[idx] = words[idx][0].upper() + words[idx][1:] if words[idx] else words[idx]
                    cmd = ' '.join(words)

            if random.random() > 0.85:
                prefixes = ['please ', 'can you ', 'hey ', 'could you ', 'I want to ', 'help me ', 'would you mind ', '']
                cmd = random.choice(prefixes) + cmd

            texts.append(cmd)
            labels.append(intent)

    return texts, labels
